try {
    let person = Karol    
} catch (error) {
    console.log('error: ', error);
} finally {
    console.log('finally block reached')
}
console.log('done');